# This dockerfile is used to build the development image for the backend
FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install pdm

RUN pdm install

WORKDIR /app/src

EXPOSE 8000

ENTRYPOINT ["sh", "-c", "\
pdm run python -u ./worker/worker.py & \
pdm run python -u ./worker/task_creator.py & \
pdm run uvicorn main:app --host=0.0.0.0 --port=8000 --reload \
"]