name: Code Check on Push

on:
  pull_request:
    branches: [main]

jobs:
  frontend-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable Corepack
        run: corepack enable

      - name: Install Yarn 2
        run: yarn set version berry
        working-directory: ./frontend

      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Run linter
        run: yarn run lint
        working-directory: ./frontend

      - name: Build
        run: yarn run build
        working-directory: ./frontend

  backend-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        working-directory: ./backend  
        run: pdm install --dev

      - name: Run linter
        working-directory: ./backend
        run: pdm run ruff .